version: "3.8"
services:
  db:
    image: postgres:16.2
    container_name: db_postgres
    restart: always
    env_file:
      - .env_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_db
    container_name: fastapi_project
    restart: always
    ports:
      - 1243:8000
    depends_on:
      - db
    command: sh migrate.sh
volumes:
  db-data:
